spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aaa?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

    username: root
    password: 151567
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
server:
  port: 8081

#mybatis-plus:
#  mapper-locations: classpath:com/aaaa/mapper/xml/*Mapper.xml
#  type-aliases-package: com.aaaa.model

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl